Description: Pattern with packages for f8131 configurations
Name: jolla-configuration-f8131
Requires:
- pattern:jolla-hw-adaptation-dora

- droid-config-f8131-sailfish
- droid-config-f8131-pulseaudio-settings
- droid-config-f8131-policy-settings
- droid-config-f8131-preinit-plugin
- droid-config-f8131-flashing
- droid-config-f8131-bluez5
- droid-hal-version-f8131

- patterns-sailfish-applications
- patterns-sailfish-ui
- patterns-sailfish-cellular-apps

- sailfish-content-graphics-z@ICON_RES@

# Introduced starting Sailfish OS 2.0.4.x:
# 3rd party accounts like Twitter, VK, cloud services, etc
- jolla-settings-accounts-extensions-3rd-party-all

# Introduced starting Sailfish OS 2.1.1.26
# Required for Jolla Store Access
- patterns-sailfish-consumer-generic

# For Mozilla location services (online)
- geoclue-provider-mlsdb

# Sailfish OS CSD tool for hardware testing
# needs some configuration to get all features working
- csd

- jolla-settings-system-flashlight

# Devices with 2G or more memory should also include this booster
# to improve camera startup times and the like
- mapplauncherd-booster-silica-qt5-media

Summary: Jolla Configuration f8131
