Description: Pattern with packages for g8232 configurations
Name: jolla-configuration-g8232
Requires:
- pattern:jolla-hw-adaptation-keyaki

- droid-config-g8232-sailfish
- droid-config-g8232-pulseaudio-settings
- droid-config-g8232-policy-settings
- droid-config-g8232-preinit-plugin
- droid-config-g8232-flashing
- droid-config-g8232-bluez5
- droid-hal-version-g8232

- patterns-sailfish-applications
- patterns-sailfish-ui
- patterns-sailfish-cellular-apps

- sailfish-content-graphics-z@ICON_RES@

- jolla-settings-system-flashlight

# Devices with 2G or more memory should also include this booster
# to improve camera startup times and the like
- mapplauncherd-booster-silica-qt5-media

Summary: Jolla Configuration g8232
