Description: Pattern with packages for f8131 configurations
Name: jolla-configuration-f8131
Requires:
- pattern:jolla-hw-adaptation-dora

- droid-config-f8131-sailfish
- droid-config-f8131-pulseaudio-settings
- droid-config-f8131-policy-settings
- droid-config-f8131-preinit-plugin
- droid-config-f8131-flashing
- droid-config-f8131-bluez5
- droid-hal-version-f8131

Summary: Jolla Configuration f8131
