Description: Pattern with packages for g8232 configurations
Name: jolla-configuration-g8232
Requires:
- pattern:jolla-hw-adaptation-keyaki

- droid-config-g8232-sailfish
- droid-config-g8232-pulseaudio-settings
- droid-config-g8232-policy-settings
- droid-config-g8232-preinit-plugin
- droid-config-g8232-flashing
- droid-config-g8232-bluez5
- droid-hal-version-g8232

# For multi-SIM devices
- jolla-settings-networking-multisim

Summary: Jolla Configuration g8232
