Description: Pattern with packages for f8331 configurations
Name: jolla-configuration-f8331
Requires:
- pattern:jolla-hw-adaptation-kagura

- droid-config-f8331-sailfish
- droid-config-f8331-pulseaudio-settings
- droid-config-f8331-policy-settings
- droid-config-f8331-preinit-plugin
- droid-config-f8331-flashing
- droid-config-f8331-bluez5
- droid-hal-version-f8331

- patterns-sailfish-applications
- patterns-sailfish-ui
- patterns-sailfish-cellular-apps

- sailfish-content-graphics-z@ICON_RES@

# Introduced starting Sailfish OS 2.0.4.x:
# 3rd party accounts like Twitter, VK, cloud services, etc
- jolla-settings-accounts-extensions-3rd-party-all

# Introduced starting Sailfish OS 2.1.1.26
# Required for Jolla Store Access
- patterns-sailfish-consumer-generic

# For Mozilla location services (online)
- geoclue-provider-mlsdb

# Sailfish OS CSD tool for hardware testing
# needs some configuration to get all features working
- csd

- jolla-settings-system-flashlight

# Devices with 2G or more memory should also include this booster
# to improve camera startup times and the like
- mapplauncherd-booster-silica-qt5-media

Summary: Jolla Configuration f8331
